govuk-one-login/authentication-smoke-tests

- ci/terraform/parameters.tf
- We don't want to create a aws_ssm_parameter for basic auth in production
> BAU - Don't create ssm param when environment is production

- ci/tasks/build.yml
- package.json
Only install production assets as the rest of the packages are already installed.
> Run yarn as production

- ci/terraform/policies.tf
Update s3 permissions to allow clearing of sms code bucket.
> Govsi 848 - update s3 permissions

- ci/terraform/alarm.tf
Add smoke test cloudwatch alarms to trigger pagerduty.
Currently set to not trigger automatically pending testing.
> GOVSI-619: add smoke test cloudwatch alarms to trigger pagerduty

- alerts-src/alerts.js
- Configure the alerts.js lambda to send ElastiCache events to slack
- Remove the 2 unused dependencies 
- The payload is different for ElastiCache events so we need to adapt the lambda so it can cater for both sets of Slack alerts.
> AUTH-1262 - Configure the alerts.js lambda to send ElastiCache events to slack

- ci/terraform/alerts.tf
- ci/terraform/pagerduty.tf
- Remove the PagerDuty Cronitor SNS topic, and related resources, as they are not used
- The SNS policy being attached to the Slack alert lambda is unnecessary. The lambda does not need any SNS permissions, as the SNS runtime handles the passing of the message.
Keeping the code clean and removing unnecessary permissions is a good thing.
> AUTH-1251: Remove redundant resources

- ci/terraform/alerts.tf
- Subscribe the Slack alerts lambda to the `core` Terraform Slack alerts channel topic also. 
We have added a new Slack alerts topic in the `core` Terraform. We will consolidate the topics used in a follow up PR and, maybe, move the alert lambdas to the `core` Terraform.
https://github.com/alphagov/di-infrastructure/pull/203
> AUTH-1375: Add Slack subscription to core slack alerts channel

- ci/tasks/deploy.yml
- ci/terraform/alerts.tf
- ci/terraform/heartbeat.tf
- ci/terraform/variables.tf
- Update the Terraform to pick up the code direct from signed code bucket.
We are now building the alert lambda and heartbeat lambda in a standalone repository and publishing signed ZIPs to an S3 bucket.
https://github.com/alphagov/di-monitoring-utils/pull/2
https://github.com/alphagov/di-infrastructure/pull/207
> AUTH-1250: Use shared artefact for alert and heartbeat

- ci/tasks/deploy.yml
- Remove the Concourse resource name from the calculated S3 key (filename) as this results in an invalid S3 key.
Pipeline is currently failing with "invalid key name" message.
#41
> AUTH-1250: Pass correct S3 key to Terraform

- src/aws.js
- src/canary.js
- Only delete the file for the phone number allocated to these tests
Clearing the entire bucket is no longer acceptable as other processes are using the bucket to pick up the SMS codes from.
> BAU: Stop clearing entire bucket

- src/aws.js
- Simplify call to delete file from bucket by using the `DeleteObject` API call rather than `DeleteObjects` as we're only deleting a single object
Call to `DeleteObjects` is failing due to invalid parameter being passed. Using `DeleteObject` makes more sense anyway as we're only deleting a single object.
#44
> BAU: Use `DeleteObject` instead of `DeleteObjects`

- src/canary.js
- Change expected page title on account management page to "Your GOV.UK account - GOV.UK account"
A change has recently been put through that has changed the title of the account managment pages.
https://github.com/alphagov/di-authentication-account-management/pull/502
> BAU: Change expected page title on account management page

- src/canary.js
- Change the ID to wait for to `#your-account`
The `#warning-link` ID has been removed in a recent change
https://github.com/alphagov/di-authentication-account-management/pull/522
> BAU: Change the known selector to wait for in account management

- ci/terraform/canary.tf
- Upgrade syn-nodejs-puppeteer version to the latest 3.8
- Our current version is deprecated on November 13th 2022 so we should upgrade to 3.8.
- This has been tested in the Integration smoke tests but upgrading the version directly in the console and it seems to be happy.
> ACI-110 - Upgrade syn-nodejs-puppeteer version to the latest 3.8

- ci/terraform/create-account.tf
- ci/terraform/modules/canary/alarm.tf
- ci/terraform/modules/canary/variables.tf
Wire alerts for create account smoketest.
- Create P1 and P2 alarms that post to the existing sns topics for PagerDuty and Slack.
- Alarms created in integration only, not production
Alerts should be fired when the create account smoke test fails.
#52
> AUT-829: Wire alerts for create account smoketest

- ci/terraform/modules/canary/parameters.tf
- ci/terraform/modules/canary/policies.tf
- ci/terraform/modules/canary/variables.tf
- src/canary-create-account.js
Add smoke test fire drill switch.  Adds an SSM parameter that causes the create account smoke test to fail when set to '1'. 
Remove try catch block wrapped around the canary handler method.
Provides facility to test that alerts are sent when the smoke test fails.
The try catch block was stopping the canary from actually failing when an error was thrown, instead it would log an error but not actually fail
#52
> AUT-829: Add smoke test fire drill switch

- ci/tasks/deploy.yml
- ci/terraform/create-account.tf
- ci/terraform/modules/canary/parameters.tf
- ci/terraform/modules/canary/policies.tf
- ci/terraform/modules/canary/variables.tf
- ci/terraform/variables.tf
- src/canary-create-account.js
Call synthetics-user delete from the create account smoke test.
- Add additional config for the test-services api synthetics-user endpoint.
- Call the endpoint at the beginning of the create account smoke test so that the test does not try to create an existing user.
- Remove the step to delete the account in Account Management.
This canary is currently running in integration only.
To delete the user create by previous test runs.
Removes the dependency on Account Management to clean up the created test user.
#52 
#54
> AUT-829: Call synthetics-user delete from the create account smoke test

- ci/terraform/alarm.tf
- ci/terraform/create-account.tf
- ci/terraform/modules/canary/canary.tf
- ci/terraform/modules/canary/policies.tf
- ci/terraform/modules/canary/roles.tf
Update canary name and alarm descriptions.
Tidy up bucket policy.
Provide more meaningful information in alert messages.
Canary names cannot exceed 21 characters so extra information added to the alert for more context.
Remove rights to an enivronment specific bucket in the bucket policy.
> AUT-829: Update canary name and alarm descriptions

- ci/terraform/modules/canary/roles.tf
Fix prod smoke test deployment.
Add counts to policies not having a parent in prod.
Terraform apply has failed as a previous PR added a 'count' = 0 to the 'smoke_tester_role' in prod without adding a corresponding 'count' to child policies.
#57
> AUT-829: Fix prod smoke test deployment

- src/canary-create-account.js
- src/canary.js
Swap AM Your Account to Your Services.
This is a temporary solution pending the complete removal of AM as a client from the tests.
The AM landing page has changed so update the smoke tests to reflect the new content.
https://github.com/alphagov/di-authentication-account-management/pull/769
> BAU: Swap AM Your Account to Your Services

- ci/tasks/deploy.yml
- ci/terraform/create-account.tf
- ci/terraform/integration-overrides.tfvars
- ci/terraform/integration-stub-clients.tfvars
- ci/terraform/modules/canary/parameters.tf
- ci/terraform/modules/canary/policies.tf
- ci/terraform/modules/canary/variables.tf
- ci/terraform/outputs.tf
- ci/terraform/sandpit-stub-clients.tfvars
- ci/terraform/stub-rp-clients.tf
- ci/terraform/variables.tf
- deploy-sandpit.sh
- package.json
- src/aws.js
- src/canary-create-account.js
- src/canary.js
- yarn.lock
Use smoke test microclient for create account smoke test in integration.
- Swaps-out Account Management as a client and replaces it with a client running in the canary itself.
- Adds terraform to create a client in the client registry for the microclient to use.
This change applies to integration only as the create account smoke test is not deployed to production.
Account Management has moved to the Accounts team so the Auth team is removing all dependencies on it from automated tests.  Ensures that the team tests (mostly) what it builds.
https://github.com/alphagov/di-authentication-api/pull/2686
Thanks to @cjfryer for the prototype: https://github.com/cjfryer/express-openid-connect-onelogin-prototype
> AUT-834: Use smoke test microclient for create account smoke test in integration

- src/canary-create-account.js
Fix smoke test microclient race condition.
Callback to the microclient had been failing roughly 50% of the time.  This was due to a race condition waiting for the various redirects to complete before the call to user-info could succeed.
See the 'Remarks' section:
https://pptr.dev/next/api/puppeteer.page.click
#61
> AUT-834: Fix smoke test microclient race condition

- ci/terraform/production-overrides.tfvars
- ci/terraform/production-stub-clients.tfvars
Add production smoke test client configuration.
The existing smoke test will be switched to use the new client.
Creating the configuration now as the pipeline deploy task now requires these files in order to run.  Fixes broken pipeline.
#61
> AUT-834: Add production smoke test client configuration

- ci/terraform/parameters.tf
- ci/terraform/policies.tf
- src/canary.js
Remove AM dependency from sign in smoketest.
Use the microclient instead.
Some linting and formatting changes.
Remove try catch block from the handler wrapper as this suppresses canary failures in some circumstances.
This will initially be rolled-out to integration only with the prod deploy job paused to stop it deploying to prod.
Removing all Auth dependencies on Account Management as the team no longer owns the app.
#61 
#64
> AUT-834: Remove AM dependency from sign in smoketest

- ci/terraform/parameters.tf
Add smoke test global ssm parameter for client id.
This parameter will be consumed by the oidc api waf configuration.
> AUT-834: Add smoke test global ssm parameter for client id

- src/canary-create-account.js
Ensure password contains letters and numbers by adding 'a1' to the end of the random password.
This smoke test (create account) is currently only running in integration.
On its own 'crypto.randomBytes' is able to generate passwords that do not contain both letters and numbers.
> AUT-829: Ensure password contains letters and numbers

- ci/terraform/variables.tf
- Add default values for integration issuer base url and password
- These are only used in sandpit so that it can 'point at' integration
- They are therefore not supplied for other environments
- Amends: https://github.com/alphagov/di-authentication-smoke-tests/pull/74
> AUT-835: Add default values for integration variables

- ci/terraform/create-account.tf
- Turn off create account smoke in integration
- Temporary measure whilst deploying new P2 smoke to avoid resource conflicts
> BAU: Turn off create account smoke in integration

- ci/terraform/canary-sign-in-with-ipv.tf
- Enable IPV/P2 journey smoke test in prod
- Changes have now been tested in integration
- Enables: https://github.com/alphagov/di-authentication-smoke-tests/pull/76 and https://github.com/alphagov/di-authentication-smoke-tests/pull/74 in production
> AUT-835: Enable IPV/P2 journey smoke test in prod

- ci/terraform/canary-sign-in-with-ipv.tf
- ci/terraform/create-account.tf
- ci/terraform/integration-overrides.tfvars
- ci/terraform/modules/canary/canary.tf
- ci/terraform/modules/canary/variables.tf
- ci/terraform/production-overrides.tfvars
- ci/terraform/sandpit.tfvars
- ci/terraform/variables.tf
- Ship smoke test logs to Splunk
- Add a aws_cloudwatch_log_group and aws_cloudwatch_log_subscription_filter terraform resource to the canary.tf module. This will allow for smoke test resources to be sent to Splunk which will allow easier access to smoke test logs.
> AUT-981 - Ship smoke test logs to Splunk

- ci/terraform/modules/canary/policies.tf
- Give canary permissions to write to the correct cloudwatch location
- It had permissions to log to `/aws/lambda/cwsyn-smoke-ipv-*` but it actually needs permission to log to `/aws/lambda/cwsyn-integration-smoke-ipv-*` which now includes the environment
> AUT-981 - Give canary permissions to write to the correct cloudwatch location

- ci/terraform/modules/canary/parameters.tf
- ci/terraform/modules/canary/policies.tf
- ci/terraform/modules/canary/roles.tf
- Remove a number of `count = {conditional on environment}` in canary base module
- Amends 58117071cc3c4380e60cb758b727758fe4144455
- Terraform module contained many references to production with zero counts associated
- These break deployment in prod
-Amends: https://github.com/alphagov/di-authentication-smoke-tests/pull/81
> AUT-835: (Correction) Remove prod smoke test module block

- ci/terraform/modules/canary/canary.tf
- Use name_prefix instead of name for aws_cloudwatch_log_group
- AWS create a cloudwatch log group for us with the name  /aws/lambda/cwsyn-MyCanaryName-randomId. We don't know what the random ID will be but we do know the prefix of the name so use that instead
> AUT-981 - Use name_prefix instead of name for aws_cloudwatch_log_group

- ci/tasks/deploy.yml
- ci/terraform/create-account.tf
- ci/terraform/variables.tf
Re-enable create account smoke test in integration.
Add separate variable for phone number so all smoke tests can use a different number.
The smoke test was deleted in order to release the ipv smoke test to both integration and production.  Way is now free to release the create account smoke test.
Each smoke test must use a separate phone number in order to receive sms otp.
#77
> AUT-829: Re-enable create account smoke test in integration

- ci/terraform/modules/canary/alarm.tf
- ci/terraform/modules/canary/canary.tf
- ci/terraform/modules/canary/parameters.tf
- ci/terraform/modules/canary/policies.tf
- ci/terraform/modules/canary/roles.tf
- Correctly name the aws cloudwatch log group
- AWS canary automatically creates a cloudwatch log group and attached the random ID to this. To ensure that the AWS canary uses our log group, we need to create one via terraform with the same expected name.
- There is no easy way to get the random ID, so we need to take the engine_arn which is outputted from the aws canary and split it on a colon. This will give us the ID as expected
- Remove count on the canary module as we can place the count on the canaries that use the module instead
- Add some depends on to ensures that the terraform dependencies are created in the correct order
> AUT-981 - Correctly name the aws cloudwatch log group

- ci/terraform/create-account.tf
Deploy the create account smoke test to production.
Requires the test-services-api to also be deployed in production, and changes to the smoke tests pipeline.
The test is running in integration but not in production.
> AUT-829: Deploy the create account smoke test to production

- ci/tasks/deploy.yml
- ci/terraform/canary-sign-in.tf
- ci/terraform/integration-overrides.tfvars
- ci/terraform/production-overrides.tfvars
- ci/terraform/sandpit.tfvars
- ci/terraform/user.tf
- ci/terraform/variables.tf
- src/canary-sign-in.js
- Create a sign in smoke test to use the canary terraform module. 
- This will mean we can reuse a lot of the terraform and eventually deprecate the existing sign in smoke test.
> AUT-981 - Create sign in smoke test using the canary module

- ci/terraform/canary-sign-in.tf
- ci/terraform/integration-overrides.tfvars
- ci/terraform/production-overrides.tfvars
- ci/terraform/sandpit.tfvars
- ci/terraform/variables.tf
- Make the sign in smoke test rate dynamic per environment 
- Set on the sign in alarm for Integration only
- Increase the rate for the new production sign in smoke test to run every 3 mins 24/7
- We have different SLAs per environment so make the cron expression which runs the sign in smoke test dynamic per environment
- Set the sign in smoke test to run the smoke tests every 3 minutes between 09:00 - 17:00 Mon - Fri for Integration
- Set the sign in smoke test to run the the smoke tests every 3 minutes 24/7 for Production
- Adjust the cron expression as per https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html
- Turn on the alerts for this lambda for Integration
> AUT-981 - Make the sign in smoke test rate dynamic per environment 

- ci/terraform/heartbeat.tf
- ci/terraform/integration-overrides.tfvars
- Switch on Cronitor for new sign in smoke test for Integration
- Add a flag so when cronitor is switched on the new smoke test, it is switched off on the old sign in smoke test. 
- This will make migration easier
> AUT-981 - Switch on Cronitor for new sign in smoke test for Integration

- ci/terraform/alarm.tf
- ci/terraform/production-overrides.tfvars
- Disable original Sign In smoke test alarm and cronitor for Production as it is being replaced with the new module smoke test
- The old sign in smoke test will be removed soon in favour of the new sign in smoke test which uses the canary module
> AUT-981 - Enable Sign In module smoke test alarms and cronitor in Production

- src/canary-create-account.js
Empty create account smoke test phone otp bucket.
Prevent exceptions when writing to the bucket during tests.
Currently seeing 'Exception thrown when writing to S3 bucket' for the phone number for this test.  This error is not seen for other smoke tests.
> AUT-923: Empty create account smoke test phone otp bucket

- .github/workflows/build.yml
GitHub Actions to build and push modules:
- builds each module, packaging as a zip
- uploads built artifact to S3
- runs signing job against artifact
Supporting efforts to move off Concourse
Depends on https://github.com/alphagov/di-infrastructure/pull/471
> GitHub Actions to build and push modules

- src/canary-sign-in-with-ipv.js
- src/canary-sign-in.js
Sign in button instead of link
The sign in link has changed to a button.
https://github.com/alphagov/di-authentication-frontend/pull/951
> AUT-1116: Sign in button instead of link

- src/canary-sign-in-with-ipv.js
Remove the Photo ID execution step as it's no longer included in pre-auth journey
Photo ID Screener not necessary due to low user usage (user's selecting No - I don't have a Photo ID)
[Changes in frontend app](https://github.com/alphagov/di-authentication-frontend/pull/962)
> AUT-1134: Remove Photo ID execution steps as not required in pre-auth journey

- ci/terraform/modules/canary/alarm.tf
- Adjust smoke test threshold to 2 failures in 10 minutes
- To ensure we are alerted quickly for any downtime that occurs
> BAU - Adjust smoke test threshold to 2 failures in 10 minutes

- src/canary-create-account.js
- src/canary-sign-in-with-ipv.js
- src/canary-sign-in.js
- Ensure that we always shut down the node server after every run by adding in a finally block similar to what we have on the IPV smoke test
- We are seeing situations where a smoke test is failing and the next smoke test fails to run because the previous smoke test has not shut down so there is a process still running on the port. The error we are seeing is `No test result returned.listen EADDRINUSE: address already in use 0.0.0.0:3031`
> AUT-1211 - Make Node server shutdown after every Smoke Test run

- ci/terraform/canary-sign-in-with-ipv.tf
- ci/terraform/create-account.tf
- ci/terraform/integration-overrides.tfvars
- Adjust times of smoke test runs
- The cron expression is in UTC which means the current IPV/Create account smoke test do not start until 11:00am. Eventually these will run 24/7 but for now adjust the times so that they start earlier
> AUT-1211 - Adjust times of smoke test runs

- ci/terraform/variables.tf
Bump Ts&Cs version to reflect new privacy policy.
This needs to be rolled out after the api change has deployed, pause the smoke tests during the integration and prod deployments.
The privacy policy has been updated.
https://github.com/alphagov/di-authentication-api/pull/2917
> BAU: Bump Ts&Cs version to reflect new privacy policy

- ci/terraform/modules/canary/canary.tf
Bump puppeteer to the latest version 4.0.
Keep the version current so that it doesn't expire unexpectedly.
> BAU: Bump puppeteer to the latest version 4.0

- ci/terraform/create-account.tf
- ci/terraform/modules/canary/canary.tf
- ci/terraform/modules/canary/variables.tf
Switch off Create Account smoke test.
Pending fix for intermittent failures.
https://govukverify.atlassian.net/browse/AUT-1333
> BAU: Switch off Create Account smoke test

- ci/terraform/production-overrides.tfvars
- Turn on PagerDuty alerting for Production IPV handoff smoke tests
- This includes Slack alerting via PagerDuty integration
- Gives quicker alerting capability where breaking changes may be introduced in sign-in journey that break IPV Core handoff
> BAU: Turn on PagerDuty alerting for Production IPV handoff smoke tests

- ci/terraform/canary-sign-in-with-ipv.tf
- Run the IPV P1 smoke test 24/7
- As it's a P1 smoke test, we need to be alerted out of hours as well as in hours if there are any issues.
> BAU - Run the IPV P1 smoke test 24/7

- src/canary-sign-in-with-ipv.js
Update ipv landing page title.
To fix failing smoke test due to the page content changing.
> BAU: Update ipv landing page title

- ci/terraform/create-account.tf
- ci/terraform/modules/canary/parameters.tf
- ci/terraform/modules/canary/policies.tf
- ci/terraform/modules/canary/variables.tf
- ci/terraform/variables.tf
Rename variables to use underscores.
New pipeline doesn't support variables with hyphens (weird bash issue).
> Rename variables to use underscores

- ci/terraform/modules/canary/parameters.tf
- ci/terraform/modules/canary/policies.tf
Renames:
test_services_api_key -> test-services-api-key
test_services_api_hostname -> test-services-api-hostname
synthetics_user_delete_path -> synthetics-user-delete-path
Likely to introduce a bug if terraform deletes the SSM parameters while in use.
> Rename SSM parameters to original values

- .github/CODEOWNERS
- CODEOWNERS
Update codeowners for new org
Team names have changed in the new org.
> BAU: Update codeowners for new org

- ci/terraform/s3.tf
Added Public block to S3 bucket
Old bucket which were created before the public Block setting was enabled at account setting are getting flagged in CPC finding as Public block missing
> AUT-2260 s3 bucket level settings public block

- deploy-sandpit.sh
- scripts/dev_deploy_common.sh
- scripts/export_aws_creds.sh
- Use well-known AWS profile names
- Pull out common code from deploy-sandpit.sh into a common script
- Pull out AWS credential export into a separate script
Local profile names were different for each person's laptop. This standardises them.
Also, it makes the deploy scripts easier to maintain.
- use python script implemented in govuk-one-login/authentication-api#4042 to create the correct AWS accounts
- deploy something to sandpit - check there are no errors
> AUT-2485: Improve Dev deployment scripts

- ci/terraform/read_secrets.sh
The read_secrets.sh is failing to read the secret
read_secrets.sh script is failing to read secret dues to outdated jq search
parse error: Invalid numeric literal at line 2, column 0
> BAU fixing read-secret script jq is outdated

- ci/terraform/alerts.tf
- ci/terraform/heartbeat.tf
Upgrade alerts and heartbeat lambdas to nodejs18.x
nodejs14.x is deprecated.
> BAU: Upgrade alerts and heartbeat lambdas to nodejs18.x

- ci/terraform/canary-sign-in-with-ipv.tf
- ci/terraform/canary-sign-in.tf
- ci/terraform/create-account.tf
- ci/terraform/modules/canary/canary.tf
Increasing the failure retention from 7 days to 14 days also increasing the canary cloud watch log retention to 7 days
> canary-Failure-and-log-retention

- ci/terraform/variables.tf
Downgrade canary runtime to 6.2.
Seeing smoketest errors which appear to have become more frequent recently. Downgrading just to rule the runtime version out as a cause of the issues.
> BAU: Downgrade canary runtime to 6.2

- ci/terraform/create-account.tf
These had been disabled since the switch from concouse to aws code pipelines, since a variable had not been migrated over, and the canaries were noisily failing. This has now been fixed, and we've trialled manually turning these alarms on in both environments, with successful runs.
The alarms will be turned on separately once we've seen a day or so of successful runs.
Fixes in the api: [integration](https://github.com/govuk-one-login/authentication-api/pull/4201) and [production](https://github.com/govuk-one-login/authentication-api/pull/4208)
> AUT-1506: Turn on create account canaries in integration and production

- ci/terraform/create-account.tf
The other smoke tests have previously been updated to do the same (although they still only run within office hours in the integration environment). Since we have now fully fixed and re-enabled the create account tests (which had previously been broken since the migration from concourse to aws pipelines), we should also run these tests on the same schedule.
Please include a summary of the change.
Please include reason for the change and any other relevant context.
Please include links to PRs in other repositories relevant to this PR.
Delete this section if not needed.
> AUT-1506: Update create account smoke tests to run 24/7 in production

- alerts/alerts.js
- alerts/aws.js
- alerts/package.json
The runtime of the alerts lambda was recently upgraded to node 18, which requires us to use version 3.x of the aws sdk. There were also some differences introduced as to how to import.
This replicates what has already been done in the slack-src directory here.
This is similar to the following change for the slack lambda when it was in a different repo: https://github.com/govuk-one-login/monitoring-utils/commit/9b99dc881e079711817ef760acaba4b1a0e16ebf
> AUT-2688: Upgrade aws dependency to 3.x

- ci/terraform/.terraform.lock.hcl
- ci/terraform/alerts.tf
- ci/terraform/canary-sign-in-with-ipv.tf
- ci/terraform/canary-sign-in.tf
- ci/terraform/create-account.tf
- ci/terraform/heartbeat.tf
- ci/terraform/modules/canary/heartbeat.tf
- ci/terraform/s3.tf
- ci/terraform/stub-rp-clients.tf
- scripts/dev_deploy_common.sh
- scripts/terraform-lint.sh
- scripts/terraform-upgrade.sh
- update provider locks
- Add helper scripts to do common terraform tasks repeatably
- Fix all linting errors in terraform after updating providers
- The locks hadn't been fully updated to lock the correct provider versions
- Helper scripts are helpful
- We were using many resources and attributes which have been deprecated, so fix these
> [AUT-2306] Update terraform provider locks, fix deprecations and add helper scripts

- ci/terraform/modules/canary/alarm.tf
We have some flakiness with smoke tests. Bumping the alerting threshold to 3 failures within the time period means that we don't send pagerduty alerts for known problems to 2nd line while we deal with the underlying root cause.
This should be reverted when the underlying problem is fixed.
> AUT-2686: Temporarily increase p1 alerting threshold

- package.json
- yarn.lock
Reverts govuk-one-login/authentication-smoke-tests#248
> Revert "BAU: Bump express-openid-connect from 2.16.0 to 2.17.1"

- ci/terraform/modules/canary/alarm.tf
This reverts commit d8d3e81bb3fa53a1538fc3d509f8d7b8c90b6593.
We previously increased the threshold at which smoke test failures would alert on a P1. This was because of a known flakey issue that has since been fixed in the frontend[1]. Sometimes these flakey issues would appear close enough together to trigger the alert.
These errors have not appeared again (there are still occassional unrelated environment errors but these do not happen often enough to cause issues) so we can restore the original thresholds.
[1]: https://github.com/govuk-one-login/authentication-frontend/pull/1575
> Revert "AUT-2686: Temporarily increase p1 alerting threshold"

- ci/terraform/alerts.tf
- ci/terraform/site.tf
As part of the cloudfront work, there will be new alerts in us-east-1. This subscribes to a new SNS topic in that region and forwards the alerts to slack.
Must be merged after https://github.com/govuk-one-login/authentication-api/pull/4310
> ATO-563: subscribe alerts lambda to cloudwatch alerts topic

- alerts/alerts.js
- ci/terraform/variables.tf
The alerts from the integration environment are causing a lot of noise in the 2nd line channel, and are on the team to investigate, not the support rota. This moves the slack notifications to a team channel.
> BAU: Move integration alerts to different slack channel

- src/helpers.js
- src/steps.js
The purpose of the smoke tests is to verify if a page loads correctly, not to validate the content in its body. Thus, it is correct to validate the page title (as it correctly reflects the status of the page) instead of the body, as the body is subject to change. This was necessary as a smoke test failure came as a result of a content body change.
Validate title, not body content, in smoke tests. 
Validating body content (that is subject to change and validation errors) causes problems.
> AUT-2729: Verify page titles instead of body

- .github/workflows/pre-merge-checks.yml
Bumped node version used in pre-merge-checks from 14 to 18
> BAU: Bump node version used in pre-merge-checks

- src/canary-create-account.js
- src/steps.js
- src/vars.js
- This fixes the potential race condition between page.waitForNavigation() and page.click() by placing both methods inside a Promise.all() block.
- Adds extra validation in checking the URL when moving from one page to the next.
- Steps have also been refactored into the steps.js file to make the test file more readable and make steps more reusable.
[1] Code review
[2] Rebase the branch over BAU/deploy-authdev1, add test services API key to the authdev1.tfvars file and run ./deploy-sandpit.sh. See that the authdev1-smoke-cra passes in cloudwatch.
> AUT-3047: Improve create account smoke tests

- heartbeat/package.json
- package.json
- src/aws.js
- yarn.lock
- Upgrade aws sdk v2 to v3
- Add 2 new aws plugins: client-s3 and client-ssm
- Change getOtpCode function to make it compatible with aws sdk v3
The aws-sdk v2 is maintenance mode on 08/09/2024
Please include reason for the change and any other relevant context.
Please include links to PRs in other repositories relevant to this PR.
Delete this section if not needed.
> Aut-2887: Upgrade aws sdk v3 in the smoke tests and alerts

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/build-and-deploy-dev.yml
- .github/workflows/build-and-deploy.yml
- .gitignore
The previous change caused the workflow [to fail and not deploy changes to the smoke tests](https://github.com/govuk-one-login/authentication-smoke-tests/actions/runs/10146347076).
Instead of the previous method of pulling in the signed smoke test zips
during the `deploy` phase, instead, retrieve them immediately after the
signing job completes in `build`, and push them up to the GHA artifact
store. Then retrieve from this store in `deploy`.
This has two benefits:
1. The artifacts are easily downloadable from github, so developers
can see exactly what it is that this workflow deployed
2. We no longer have to use the `aws s3 cp` globbing to retrieve the
correct artifact version: we can just retrieve the specific key
that the signing job returns.
Ensure that this branch pushes the correct …
> BAU: Fix smoke test deployment

- .github/workflows/pre-commit.yml
- alerts/alerts.js
Log raw sns messages.
Some messages are failing to be parsed by 'buildMessageRequest' so adding additional logging to see which messages are causing the issue.
```
{
"errorType": "TypeError",
"errorMessage": "Cannot read properties of undefined (reading 'split')",
"stack": [
"TypeError: Cannot read properties of undefined (reading 'split')",
"    at formatMessage (/var/task/alerts.js:4:49)",
"    at buildMessageRequest (/var/task/alerts.js:67:16)",
"    at Runtime.handler (/var/task/alerts.js:93:26)",
"    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
]
}
```
1. Code Review
> BAU: Log raw sns messages

- .github/dependabot.yml
This reduces the number of PRs that have similar version bumps for AWS npm dependencies.
At the time of drafting this PR, we have 6 open PRs for AWS npm updates. This would reduce that to 3 and tie intrinsically linked dependency updates together for each application in this repo.
- https://github.com/govuk-one-login/authentication-smoke-tests/pull/927
- https://github.com/govuk-one-login/authentication-smoke-tests/pull/926
- https://github.com/govuk-one-login/authentication-smoke-tests/pull/925
- https://github.com/govuk-one-login/authentication-smoke-tests/pull/924
- https://github.com/govuk-one-login/authentication-smoke-tests/pull/923
- https://github.com/govuk-one-login/authentication-smoke-tests/pull/922
We can see with the last two how they can become desynced.
1. Code Review
> BAU: Group AWS npm dependabot PRs

- ci/terraform/production-overrides.tfvars
AUT-3694 : As part of Auth frontend migration we want to run Smoke test every minute in prod so  updating the Cron job to run  smoke-test every minute in prod
1. Code Review
> AUT-3694: updating the Cron job to run  smoke-test every minute in prod

- ci/terraform/integration-overrides.tfvars
Revert to run integration smoke tests every 3 mins
Suspected flakiness caused by increased frequency
1. Code Review
https://github.com/govuk-one-login/authentication-smoke-tests/pull/1026
> BAU: revert to run integration smoke tests every 3 mins

- ci/terraform/sandpit.tfvars
* Makes sure that each of these numbers are different, meaning we can run the tests at the same time without risk of interference
* Uses the notify test numbers[1] to ensure that these do not trigger actual failed attempts to send to a number
This comes off the back of an incident where our smoke tests were using an offcom reserved number (07700900333) that is not also a notify test number. This was causing notify to attempt to send to this number but failing each time a smoke test using this number ran. At some point, we had enough failures to this number to trigger a warning from Notify, so we are fixing usages of this number to instead be one of the reserved notify test numbers.
This was largely a problem with the integration and production values which are stored in aws rather than …
> AUT-4043: Update smoke test numbers for sandpit canaries

- ci/terraform/production-overrides.tfvars
Reverts govuk-one-login/authentication-smoke-tests#1039 which was temp increase in frequency of Smoke test in prod for frontend Migration 
Auth Prod Frontend is Successfully migrated and we have monitored the change for 2 weeks all good so reverting this change
> Revert "AUT-3694: updating the Cron job to run  smoke-test every minute in prod"

- package.json
- yarn.lock
Reverts govuk-one-login/authentication-smoke-tests#1093
> Revert "BAU: Bump express-openid-connect from 2.17.1 to 2.18.0"

- src/steps.js
IPV recently updated the title string of the IPV handoff expected page, meaning the IPV smoke test fails without this change to match.
1. Code Review
- https://github.com/govuk-one-login/ipv-core-front/pull/2019
> BAU: Update step to match IPV content change

- alerts/alerts.js
Use Slack ID for all low environment in alert lambda
1. Code Review
> Use Slack ID for all low environment in alert lambda

- ci/terraform/modules/canary/canary.tf
Previously, the lambda associated with the canary would be left behind
when updating the canary. Now, we create a new lambda, and delete the
old one.
0. Look at the AWS console in staging, take note of the latest canary lambdas
1. make a change to the lambda code (so the canary is seen as 'different')
2. deploy to sandpit
3. observe that the previously noted lambdas have been removed, and new ones created in their place
> BAU: Remove old canary lambda when updating

- ci/terraform/stub-rp-clients.tf
This enforces a rate limit of 5 req/minute from the smoke test RP
> BAU: Add rate limit for smoke test RPs

- ci/terraform/production-overrides.tfvars
- template.yaml
Update the smoke tests in prod to run every minute instead of every 3 minutes. This is because of incident INC0014859, where with the current frequency, it can take up to 5.5 minutes from downtime to us being alerted, and it was decided that there's not downside to running these more often, so the maximum downtime to being alerted has been reduced to 1.5 minutes with this frequency.
> ATO-1859: update prod smoke tests to run every minute

- heartbeat/heartbeat.js
Instead of logging the full key, hide all but the last 3. This means less risk of exposure.
1. Code Review
> BAU: Hide most characters of Cronitor key

- template.yaml
synthetics canary are not getting deployed so we need to pass the version ID s3 object , PR is adding a custom resource to fetch the head version s3 object ( synthetics.zip) and pass as ref to Canary deployment 
Add s3 object to synthetics canary to force new deployment
1. Code Review
1. Deploy to authdev3 and see canary is getting deployed
> bau: Add s3 object to synthetics canary to force new deployment
