govuk-one-login/authentication-smoke-tests

src/canary.js
Add try catch to handle error logging.
=> Add try catch to handle error logging

alerts-src/alerts.js
Please include a summary of the change.
Please include reason for the change and any other relevant context.
Please include links to PRs in other repositories relevant to this PR.
Delete this section if not needed.
=> BAU - Amend alert description

src/canary.js
Update smoke test with sign in page changes
=> Update smoke test with sign in page changes

src/canary.js
We're trying to debug the "disappearance" of an id which is failing the smoke tests.
=> BAU: Update selector temporarily for debugging

src/canary.js
The page title has changed since last release
=> BAU: Update page title temporarily for debugging

src/canary.js
Debugging complete, rolling back these changes
=> BAU: Revert debugging changes

src/canary-create-account.js
Fix smoke test create syntax error.
A type sneaked in as there is no compilation step for javascript.
#62
=> AUT-834: Fix smoke test create syntax error

src/canary.js
Check correct email in smoke test user-info step.
Email was not defined in the user-info step scope.
#66
=> AUT-834: Check correct email in smoke test user-info step

ci/terraform/parameters.tf, ci/terraform/policies.tf, src/canary.js
Reverts alphagov/di-authentication-smoke-tests#66
=> Revert "AUT-834: Remove AM dependency from sign in smoketest"

.eslintrc.json, .github/workflows/pre-merge-checks-terraform.yml, .github/workflows/pre-merge-checks.yml, package.json, src/canary-create-account.js, src/canary.js, src/client.js
Add GHA pre-merge checks.
Reformat and add lint exceptions where required.
Enabling linting and format check will catch errors before js code is deployed.
=> AUT-834: Add GHA pre-merge checks

package-lock.json, package.json, yarn.lock
Reverts alphagov/di-authentication-smoke-tests#112
=> Revert "BAU: Bump aws-sdk from 2.1312.0 to 2.1356.0"

src/canary-sign-in-with-ipv.js
- Update the check on the IPV smoke test
- The content on the IPV smoke test has changed which has caused the smoke test to fail. Update the text we check with the new page
=> BAU - Update the check on the IPV smoke test

.github/workflows/pre-merge-checks.yml, .github/workflows/sonar-analysis-on-merge.yml, sonar-project.properties
- Add SonarCloud scanning both on PR and post-merge
- To improve code quality and security
=> AUT-1611: Add Sonar scan

sonar-project.properties
Update Sonar organisation
The repository has been moved to a new organisation in Sonar
=> BAU: Update Sonar organisation

ci/terraform/canary-sign-in-with-ipv.tf, ci/terraform/canary-sign-in.tf, ci/terraform/create-account.tf, ci/terraform/integration-overrides.tfvars, ci/terraform/modules/canary/canary.tf, ci/terraform/modules/canary/variables.tf, ci/terraform/variables.tf
This upgrades the runtime for the synthetics in the integration environment only
=> BAU: Upgrade synthetics runtime

ci/terraform/integration-overrides.tfvars, ci/terraform/variables.tf
This rolls out the most recent version of synthetics runtime across everything
=> BAU: Roll out new version across everything

src/canary-sign-in.js
Update title for first page in sign in smoke test
Title was changed as part of a content change.
https://github.com/govuk-one-login/authentication-frontend/pull/1542
=> INC: Update title for first page in sign in smoke test

src/canary-sign-in.js
Update text to match on sign in or create page for sign in test
Text has been modified in the application.
https://github.com/govuk-one-login/authentication-frontend/pull/1564
=> INC: Update text to match on sign in or create page for sign in test

src/canary-sign-in.js
Reverts govuk-one-login/authentication-smoke-tests#436
=> Revert "INC: Update text to match on sign in or create page for sign in test"

src/steps.js
Update ipv handoff page title text.
From the page:
<title lang="en">Tell us if you have one of the following types of photo ID – GOV.UK One Login</title>
The text has just been changed so the test is failing.
=> INC-761: Update ipv handoff page title text

ci/terraform/alerts.tf
=> ATO-563: pass SNS topic arn

ci/terraform/alerts.tf
Pass missing environment variable
#507
=> BAU: pass slack channel ID to alert function

src/steps.js
Restore missing 'ipvHandOff' function.
Function was deleted by mistake.
#559
=> AUT-2584: restore missing 'ipvHandOff' function

.github/workflows/build-and-deploy-dev.yml, .github/workflows/build-and-deploy.yml
frontend -> "Smoke Tests". Missed a replace when copying this over.
=> BAU: fix a typo

.github/dependabot.yml
Added a group for github actions to the dependabot config.
1. Code Review
=> BAU: Adding group for github actions to reduce the number of PRs.

.github/workflows/require-pinned-github-actions.yml
=> BAU: require pinned github actions

.github/workflows/build-and-deploy-sp.yml, template.yaml
[AUT-4434]
Initial Smoke test Sp deployment GHA setup
1. Code Review
[AUT-4434]: https://govukverify.atlassian.net/browse/AUT-4434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Initial Smoke test Sp deployment GHA setup

.github/workflows/build-and-deploy-sp.yml, .github/workflows/pre-merge-checks-sam.yml, .gitignore, package.json, template.yaml, utils/package.json, utils/randomstring.js, utils/rsakeygenerator.js
AUT-4435 smoke test build cf template
1. Code Review
=> AUT-4435 smoke test build cf template

template.yaml
remove SNS subscription for OIDC CloudFront , template is deployed in eu-west-2 region subscription is needed in us east region 
1. Code Review
=> remove SNS subscription for OIDC cloudfront

template.yaml
Update the Local host port no to 3031 
1. Code Review
=> Update the Local host port no

template.yaml
Remove SNS Subscription for All lower env
1. Code Review
=> Remove SNS Subscription for All lower env

template.yaml
Update Smoke test Cron time
For example:
1. Code Review
=> Update Smoke test Cron time

.github/workflows/build-and-deploy-dev-sp.yml, .github/workflows/build-and-deploy-sp.yml, package.json, template.yaml
Testing New promotion script in Secure pipeline canary  source code promotion
<!-- Describe the steps required to review this PR.
For example:
1. Code Review
=> Testing New promotion script

scripts/create-stub-rp-client.sh
Sync the rate limit for RP client with terraform
1. Code Review
=> Sync the rate limit for RP client with terraform

.github/workflows/build-and-deploy-dev-sp.yml, .github/workflows/build-and-deploy-sp.yml
Pin the dev platform upload action
1. Code Review
=> Pin the dev platform upload action

template.yaml
AUT-4694 Add Splunk forwarding to prod
1. Code Review
=> Add Splunk forwarding to prod

template.yaml
AUT-4694: Enable pager duty on prod and read OIDc url from secret
1. Code Review
=> AUT-4694: Enable pagerduty on prod and read OIDc url from secret

template.yaml
Update dimensions name in Alarm
Fixes INC0015235
1. Code Review
=> INC0015235: Update dimensions name in Alarm

README.md, sam-deploy-authdevs.sh, scripts/authdev3-samconfig.toml, template.yaml
AUT-4732 : Deploy Deploy smoke test in  Authdev3
1. Code Review
=> Deploy smoke test authdev3

sam-deploy-authdevs.sh, template.yaml
BAU: fix smoke test deployment in authdev3
1. Code Review
=> BAU: fix smoke test deployment in Authdev3

sam-deploy-authdevs.sh, src/canary-create-account.js, src/canary-sign-in-with-ipv.js, src/canary-sign-in.js, src/client.js, template.yaml
Added a new test header to the requests because WAF.
=> ATO-1900: add unique header
